---
- name: Pull sources from the repository using git clone.
  git: repo={{symfony2_project_repo}} dest={{symfony2_project_root}}/releases/{{symfony2_project_release}} version={{symfony2_project_branch}} accept_hostkey={{symfony2_ssh_accept_hostkey}} depth=1

- name: Clean out versioning.
  file: state=absent path={{symfony2_project_root}}/releases/{{symfony2_project_release}}/.git
  when: symfony2_project_clean_versioning == true
